### ISSUE TITLE
upgrade to angular 8 and using Ivy

### ISSUE THREAD

**Issue by MetaiR** [fingerpich/jalali-angular-datepicker#110]
hi,
I got this error after updated my project to angular 8 and enabling Ivy compiler:
```
ERROR in node_modules/ng2-jalali-date-picker/date-picker.module.d.ts(7,22): error TS-996002: Appears in the NgModule.imports of UserDetailsModule, but could not be resolved to an NgModule class
src/__ng_typecheck__.ts(33,60): error TS2344: Type '"_modal"' does not satisfy the constraint '"onClick"'.
```

**Comment by fingerpich** [comment]
Hi thanks,
I haven't tested it with angular 8 yet
can you provide a demo in stackblitz?

**Comment by MetaiR** [comment]
I can't because it wont be compiled and the error I sent, happened on compile time

**Comment by fingerpich** [comment]
If you found the problem please create a PR.

**Comment by MetaiR** [comment]
it is something about the code,
I think u must update it

**Comment by fingerpich** [comment]
We are here to collaborate and improve the project together

**Comment by faridv** [comment]
I just updated my project to Angular 9 and since Ivy is the default rendering engine and Renderer is no longer available my project doesn't work anymore. As far as I know, migrating from Renderer to Renderer2 is not an issue. Can you please update to Renderer2?

**Comment by faridv** [comment]
I think this link might help:
https://angular.io/guide/migration-renderer

**Comment by khalilifar** [comment]
My project broke too after upgrading to angular 9 I see there is also a pull request to solve this problem it's not much work mostly done by angular cli. can you please update the project to work with angular 9.

**Comment by fingerpich** [comment]
It has been fixed through #121 #122 #127
Have you  installed v2.4.2?

**Comment by khalilifar** [comment]
Yes, I have.
 The problem still exists.
I even checked with a [fresh angular 9 project](https://github.com/khalilifar/jalalidate-test.git) to make sure the problem is not just related to my project.
It also seems the jalali-moment library is broken as well. it gives the below error.
```
ERROR TypeError: Cannot read property 'calSystem' of undefined
    at isInputJalali (jalali-moment.js:579)
    at makeMoment (jalali-moment.js:590)
    at jMoment (jalali-moment.js:672)
    at UtilsService.getDefaultDisplayDate (ng2-jalali-date-picker.js:432)
    at DatePickerComponent.init (ng2-jalali-date-picker.js:1772)
    at DatePickerComponent.ngOnInit (ng2-jalali-date-picker.js:1696)
    at callHook (core.js:4726)
    at callHooks (core.js:4690)
    at executeInitAndCheckHooks (core.js:4630)
    at refreshView (core.js:12013)
```
can you maybe clone the [empty ng9 project](https://github.com/khalilifar/jalalidate-test.git) that I created and see if you can get it to work?
you might also want to check out [this pull request](https://github.com/fingerpich/jalali-angular-datepicker/pull/120)

**Comment by fingerpich** [comment]
sorry I don't use this package anymore and i cant spend enough time for this
but i fixed the problem with jalali-moment
the mentioned PR has too much changes and i couldn't test it completely,
if you can fix the problems please let me know zarei.bs@gmail.com

**Comment by khalilifar** [comment]
@fingerpich Hey, it seems the problem is solved.  looks like it was jalali-moment package and not the date-picker. Thanks a lot
